# Generated by Django 4.2.2 on 2023-07-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaucerRoster', '0003_remove_post_flavor_rating_remove_post_spice_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='none', max_length=2000),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
