# Generated by Django 4.2.2 on 2023-07-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaucerRoster', '0005_alter_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='flavor_rating',
            new_name='flavor',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='spice_rating',
            new_name='spice',
        ),
    ]
