# Generated by Django 4.2.2 on 2023-07-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaucerRoster', '0006_rename_flavor_rating_rating_flavor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='post',
            name='product',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
