# Generated by Django 4.2.2 on 2023-08-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaucerRoster', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
