# Generated by Django 4.2.2 on 2023-08-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaucerRoster', '0009_remove_post_comments_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='flavor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='spice',
            field=models.IntegerField(default=0),
        ),
    ]
