# Generated by Django 4.2.2 on 2023-08-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaucerRoster', '0015_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentwwww',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
