# Generated by Django 4.2.2 on 2023-08-25 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaucerRoster', '0019_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 11, 9, 26, 852128)),
        ),
    ]
